<p><?=$this->actionLink('Administración de Eventos Destacados','evento','index', array(), array('class' => 'h3'))?></p>
<p><?=$this->actionLink('Administración de Usuario','usuario','index', array(), array('class' => 'h3'))?></p>
<h3>Administración de Tablas del Sistema</h3>
<p style=padding-left:20px;><?=$this->actionLink('Categorías', 'categoria','index', array(), array('class' => 'categorias')) ?></p>
<p style=padding-left:20px;><?=$this->actionLink('Subcategorías', 'subcategoria','index', array(), array('class' => 'subcategorias')) ?></p>
<p style=padding-left:20px;><?=$this->actionLink('Etiquetas de Tema', 'tema','index', array(), array('class' => 'etiquetatema')) ?></p>
<p style=padding-left:20px;><?=$this->actionLink('Etiquetas de Lugar', 'lugar','index', array(), array('class' => 'etiquetalugar')) ?></p>
<p style=padding-left:20px;><?=$this->actionLink('Etiquetas de Sesión', 'sesion','index', array(), array('class' => 'etiquetasesion')) ?></p>
<p style=padding-left:20px;><?=$this->actionLink('Migrar Fotos', 'administracion','migrate') ?></p>
