<h3>Sesión - Detalle</h3>
<p>
<?=$this->actionLink('Volver al listado', 'sesion', 'index', array(), array('class'=>'back')) ?>
<br style="clear:both" />
</p>
<dl class="view">
	<dt>Descripción:</dt>
	<dd><?=$this->escape($this->sesion->descripcion) ?>&nbsp;</dd>
</dl>
<div class="actions">
<?=$this->actionLink('Editar', 
	'sesion','edit',
	array('id' => $this->sesion->id), array('class'=>'edit'),
	true, array('class'=>'edit disabled')) ?>
<?=(!models_Sesion::isInUse($this->sesion->id))? $this->actionLink('Eliminar', 'sesion','delete',array('id' => $this->sesion->id), array('onclick' =>'if(confirmDelete()){return true}else{return false}', 'class' => 'delete'),
	true, array('class'=>'delete disabled')) : '<span class="delete disabled">Eliminar</span>' ?>
</div>
<br style="clear: both"/>