<?php
$this->headScript()->appendFile($this->baseUrl . 'scripts/gridsearch.js');
$grid = $this->grid;
?>
<h3>Etiquetas de Temas</h3>
<p><?=$this->actionLink('Volver al listado', 'administracion', 'index', array(), array('class'=>'back'))?></p>
<p><?=$this->actionLink('Nuevo tema', 'tema','edit', array(), array('class'=>'nuevaetiquetatema')) ?></p>
<? if ($grid['dofilter'] == 'false' && count((array)$grid['aData']) == 0 ): ?>
	<p class="message">(no se han cargado temas)</p>
<? else: ?>
	<table class="grid" id="tbl_tema">
		<thead>
			<tr>
				<th>
					<span class="<?=$grid['tema_descripcion_className']?>">
						<a href="#" onclick="setFormValue('tema:tema_descripcion', 'grid::order', false);setFormValue('<?=$grid['tema_descripcion_sense']?>', 'grid::sense', true);">Tema</a>
					</span>
				</th>
	
				<th>Acciones</th>
			</tr>
			<tr id="search_params" class="search_params">
				<td>
					<input type="text" name="search_tema:tema_descripcion" id="search_tema:tema_descripcion" value="<?=$grid['tema_descripcion_searchKey'] ?>">
				</td>
				<td class="actions">
					<div>
					<a href="#" class="filter" onclick="gridSearch('search_params','grid');return false;">Filtrar</a>
					<a href="#" class="unfilter" onclick="gridNoSearch('search_params','grid');return false;">Quitar Filtro</a>
					</div>
				</td>
			</tr>
		</thead>
		<tbody>
		<? $odd = true; ?>
		<? foreach ((array)$grid['aData'] as $row): ?>
			<tr class="<?=($odd)?'odd':'even' ?>">
			<? $odd = !$odd; ?>
				<td><?=$this->escape($row['tema_descripcion']) ?></td>
				<td class="actions">
					<div>
					<?=$this->actionLink('Ver', 
						'tema','view',
						array('id' => $row['tema_id']), array('class'=>'view'),
						true, array('class'=>'view disabled'))?>	
					<?=$this->actionLink('Editar', 
						'tema','edit',
						array('id' => $row['tema_id']), array('class'=>'edit'),
						true, array('class'=>'edit disabled')) ?>
					<? if(!models_Tema::isInUse($row['tema_id'])): ?>
						<?=$this->actionLink('Eliminar', 
							'tema','delete',
							array('id' => $row['tema_id']), array('onclick' =>'if(confirmDelete()){return true}else{return false}', 'class' => 'delete'),
							true, array('class'=>'delete disabled')) ?>
					<? else: ?> 
						<span class="delete disabled">Eliminar</span>
					<? endif; ?>
					</div>
				</td>
			</tr>
		<? endforeach; ?>
		<tr><td colspan='2' class="gridLast"></td></tr>
		</tbody>
	</table>
<? endif; ?>
<?=$this->dataGridPager('grid') ?>
<?=$this->dataGridSubmit() ?>

