<?php

/**
 * BaseSesion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descripcion
 * @property integer $usuario_id
 * @property timestamp $created_at
 * @property integer $created_by
 * @property timestamp $updated_at
 * @property integer $updated_by
 * @property timestamp $deleted_at
 * @property integer $deleted_by
 * @property Usuario $Usuario
 * @property Doctrine_Collection $Fotografias
 * 
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method integer             getUsuarioId()   Returns the current record's "usuario_id" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method integer             getCreatedBy()   Returns the current record's "created_by" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method integer             getUpdatedBy()   Returns the current record's "updated_by" value
 * @method timestamp           getDeletedAt()   Returns the current record's "deleted_at" value
 * @method integer             getDeletedBy()   Returns the current record's "deleted_by" value
 * @method Usuario             getUsuario()     Returns the current record's "Usuario" value
 * @method Doctrine_Collection getFotografias() Returns the current record's "Fotografias" collection
 * @method Sesion              setDescripcion() Sets the current record's "descripcion" value
 * @method Sesion              setUsuarioId()   Sets the current record's "usuario_id" value
 * @method Sesion              setCreatedAt()   Sets the current record's "created_at" value
 * @method Sesion              setCreatedBy()   Sets the current record's "created_by" value
 * @method Sesion              setUpdatedAt()   Sets the current record's "updated_at" value
 * @method Sesion              setUpdatedBy()   Sets the current record's "updated_by" value
 * @method Sesion              setDeletedAt()   Sets the current record's "deleted_at" value
 * @method Sesion              setDeletedBy()   Sets the current record's "deleted_by" value
 * @method Sesion              setUsuario()     Sets the current record's "Usuario" value
 * @method Sesion              setFotografias() Sets the current record's "Fotografias" collection
 * 
 * @package    Fotiar
 * @subpackage model
 * @author     Danilo R. Frid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSesion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sesion');
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('deleted_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('deleted_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Fotografia as Fotografias', array(
             'local' => 'id',
             'foreign' => 'sesion_id'));
    }
}