<?php

/**
 * BaseRol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $id
 * @property string $descripcion
 * 
 * @method enum   getId()          Returns the current record's "id" value
 * @method string getDescripcion() Returns the current record's "descripcion" value
 * @method Rol    setId()          Sets the current record's "id" value
 * @method Rol    setDescripcion() Sets the current record's "descripcion" value
 * 
 * @package    Fotiar
 * @subpackage model
 * @author     Danilo R. Frid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rol');
        $this->hasColumn('id', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'admin',
              1 => 'fotografo',
             ),
             'primary' => true,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}