<?php

/**
 * BaseBusqueda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $categoria_id
 * @property integer $subcategoria_id
 * @property float $preciomin
 * @property float $preciomax
 * @property timestamp $fechainicial
 * @property timestamp $fechafinal
 * @property string $etiquetalugar
 * @property string $etiquetatema
 * @property string $idetiquetalugar
 * @property string $idetiquetatema
 * @property integer $reviewed
 * @property integer $untagged
 * @property integer $sesion_id
 * @property string $ordenbusqueda
 * @property integer $carga_id
 * @property timestamp $created_at
 * @property integer $created_by
 * @property timestamp $updated_at
 * @property integer $updated_by
 * @property timestamp $deleted_at
 * @property integer $deleted_by
 * 
 * @method integer   getUsuarioId()       Returns the current record's "usuario_id" value
 * @method integer   getCategoriaId()     Returns the current record's "categoria_id" value
 * @method integer   getSubcategoriaId()  Returns the current record's "subcategoria_id" value
 * @method float     getPreciomin()       Returns the current record's "preciomin" value
 * @method float     getPreciomax()       Returns the current record's "preciomax" value
 * @method timestamp getFechainicial()    Returns the current record's "fechainicial" value
 * @method timestamp getFechafinal()      Returns the current record's "fechafinal" value
 * @method string    getEtiquetalugar()   Returns the current record's "etiquetalugar" value
 * @method string    getEtiquetatema()    Returns the current record's "etiquetatema" value
 * @method string    getIdetiquetalugar() Returns the current record's "idetiquetalugar" value
 * @method string    getIdetiquetatema()  Returns the current record's "idetiquetatema" value
 * @method integer   getReviewed()        Returns the current record's "reviewed" value
 * @method integer   getUntagged()        Returns the current record's "untagged" value
 * @method integer   getSesionId()        Returns the current record's "sesion_id" value
 * @method string    getOrdenbusqueda()   Returns the current record's "ordenbusqueda" value
 * @method integer   getCargaId()         Returns the current record's "carga_id" value
 * @method timestamp getCreatedAt()       Returns the current record's "created_at" value
 * @method integer   getCreatedBy()       Returns the current record's "created_by" value
 * @method timestamp getUpdatedAt()       Returns the current record's "updated_at" value
 * @method integer   getUpdatedBy()       Returns the current record's "updated_by" value
 * @method timestamp getDeletedAt()       Returns the current record's "deleted_at" value
 * @method integer   getDeletedBy()       Returns the current record's "deleted_by" value
 * @method Busqueda  setUsuarioId()       Sets the current record's "usuario_id" value
 * @method Busqueda  setCategoriaId()     Sets the current record's "categoria_id" value
 * @method Busqueda  setSubcategoriaId()  Sets the current record's "subcategoria_id" value
 * @method Busqueda  setPreciomin()       Sets the current record's "preciomin" value
 * @method Busqueda  setPreciomax()       Sets the current record's "preciomax" value
 * @method Busqueda  setFechainicial()    Sets the current record's "fechainicial" value
 * @method Busqueda  setFechafinal()      Sets the current record's "fechafinal" value
 * @method Busqueda  setEtiquetalugar()   Sets the current record's "etiquetalugar" value
 * @method Busqueda  setEtiquetatema()    Sets the current record's "etiquetatema" value
 * @method Busqueda  setIdetiquetalugar() Sets the current record's "idetiquetalugar" value
 * @method Busqueda  setIdetiquetatema()  Sets the current record's "idetiquetatema" value
 * @method Busqueda  setReviewed()        Sets the current record's "reviewed" value
 * @method Busqueda  setUntagged()        Sets the current record's "untagged" value
 * @method Busqueda  setSesionId()        Sets the current record's "sesion_id" value
 * @method Busqueda  setOrdenbusqueda()   Sets the current record's "ordenbusqueda" value
 * @method Busqueda  setCargaId()         Sets the current record's "carga_id" value
 * @method Busqueda  setCreatedAt()       Sets the current record's "created_at" value
 * @method Busqueda  setCreatedBy()       Sets the current record's "created_by" value
 * @method Busqueda  setUpdatedAt()       Sets the current record's "updated_at" value
 * @method Busqueda  setUpdatedBy()       Sets the current record's "updated_by" value
 * @method Busqueda  setDeletedAt()       Sets the current record's "deleted_at" value
 * @method Busqueda  setDeletedBy()       Sets the current record's "deleted_by" value
 * 
 * @package    Fotiar
 * @subpackage model
 * @author     Danilo R. Frid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBusqueda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('busqueda');
        $this->hasColumn('usuario_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('categoria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('subcategoria_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('preciomin', 'float', null, array(
             'type' => 'float',
             'length' => '',
             ));
        $this->hasColumn('preciomax', 'float', null, array(
             'type' => 'float',
             'length' => '',
             ));
        $this->hasColumn('fechainicial', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('fechafinal', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('etiquetalugar', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('etiquetatema', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('idetiquetalugar', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('idetiquetatema', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('reviewed', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('untagged', 'integer', 1, array(
             'type' => 'integer',
             'length' => 1,
             ));
        $this->hasColumn('sesion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('ordenbusqueda', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('carga_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('updated_by', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('deleted_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('deleted_by', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}