<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('fotografia_frontuser', array(
             'id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'fotografia_id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '',
              'primary' => '',
              'notnull' => '',
              'autoincrement' => '',
              'length' => '4',
             ),
             'sfguarduser_id' => 
             array(
              'type' => 'integer',
              'fixed' => '0',
              'unsigned' => '',
              'primary' => '',
              'notnull' => '',
              'autoincrement' => '',
              'length' => '4',
             ),
             'status' => 
             array(
              'type' => 'enum',
              'fixed' => '0',
              'unsigned' => '',
              'values' => 
              array(
              0 => 'favorita',
              1 => 'papelera',
              2 => 'carrito',
              3 => 'comprada',
              ),
              'primary' => '',
              'default' => 'admin',
              'notnull' => '1',
              'autoincrement' => '',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('fotografia_frontuser');
    }
}