<?php

/**
 * BaseCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descripcion
 * @property timestamp $created_at
 * @property integer $created_by
 * @property timestamp $updated_at
 * @property integer $updated_by
 * @property timestamp $deleted_at
 * @property integer $deleted_by
 * @property Doctrine_Collection $Fotografias
 * @property Doctrine_Collection $Subcategorias
 * @property Doctrine_Collection $Eventos
 * 
 * @method string              getDescripcion()   Returns the current record's "descripcion" value
 * @method timestamp           getCreatedAt()     Returns the current record's "created_at" value
 * @method integer             getCreatedBy()     Returns the current record's "created_by" value
 * @method timestamp           getUpdatedAt()     Returns the current record's "updated_at" value
 * @method integer             getUpdatedBy()     Returns the current record's "updated_by" value
 * @method timestamp           getDeletedAt()     Returns the current record's "deleted_at" value
 * @method integer             getDeletedBy()     Returns the current record's "deleted_by" value
 * @method Doctrine_Collection getFotografias()   Returns the current record's "Fotografias" collection
 * @method Doctrine_Collection getSubcategorias() Returns the current record's "Subcategorias" collection
 * @method Doctrine_Collection getEventos()       Returns the current record's "Eventos" collection
 * @method Categoria           setDescripcion()   Sets the current record's "descripcion" value
 * @method Categoria           setCreatedAt()     Sets the current record's "created_at" value
 * @method Categoria           setCreatedBy()     Sets the current record's "created_by" value
 * @method Categoria           setUpdatedAt()     Sets the current record's "updated_at" value
 * @method Categoria           setUpdatedBy()     Sets the current record's "updated_by" value
 * @method Categoria           setDeletedAt()     Sets the current record's "deleted_at" value
 * @method Categoria           setDeletedBy()     Sets the current record's "deleted_by" value
 * @method Categoria           setFotografias()   Sets the current record's "Fotografias" collection
 * @method Categoria           setSubcategorias() Sets the current record's "Subcategorias" collection
 * @method Categoria           setEventos()       Sets the current record's "Eventos" collection
 * 
 * @package    Fotiar
 * @subpackage model
 * @author     Danilo R. Frid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria');
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('deleted_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('deleted_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Fotografia as Fotografias', array(
             'local' => 'id',
             'foreign' => 'categoria_id'));

        $this->hasMany('Subcategoria as Subcategorias', array(
             'local' => 'id',
             'foreign' => 'categoria_id'));

        $this->hasMany('Evento as Eventos', array(
             'local' => 'id',
             'foreign' => 'categoria_id'));
    }
}