<?php

/**
 * BaseTema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $descripcion
 * @property timestamp $created_at
 * @property integer $created_by
 * @property timestamp $updated_at
 * @property integer $updated_by
 * @property timestamp $deleted_at
 * @property integer $deleted_by
 * @property Doctrine_Collection $Fotografias
 * 
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method integer             getCreatedBy()   Returns the current record's "created_by" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method integer             getUpdatedBy()   Returns the current record's "updated_by" value
 * @method timestamp           getDeletedAt()   Returns the current record's "deleted_at" value
 * @method integer             getDeletedBy()   Returns the current record's "deleted_by" value
 * @method Doctrine_Collection getFotografias() Returns the current record's "Fotografias" collection
 * @method Tema                setDescripcion() Sets the current record's "descripcion" value
 * @method Tema                setCreatedAt()   Sets the current record's "created_at" value
 * @method Tema                setCreatedBy()   Sets the current record's "created_by" value
 * @method Tema                setUpdatedAt()   Sets the current record's "updated_at" value
 * @method Tema                setUpdatedBy()   Sets the current record's "updated_by" value
 * @method Tema                setDeletedAt()   Sets the current record's "deleted_at" value
 * @method Tema                setDeletedBy()   Sets the current record's "deleted_by" value
 * @method Tema                setFotografias() Sets the current record's "Fotografias" collection
 * 
 * @package    Fotiar
 * @subpackage model
 * @author     Danilo R. Frid
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tema');
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('deleted_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('deleted_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Fotografia as Fotografias', array(
             'refClass' => 'FotografiaTema',
             'local' => 'tema_id',
             'foreign' => 'fotografia_id'));
    }
}