<?php

/**
 * ConfSeguridadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfSeguridadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConfSeguridadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConfSeguridad');
    }
}