<?php

/**
 * FotografiaTemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FotografiaTemaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FotografiaTemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FotografiaTema');
    }
}