<?php

/**
 * FotografiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FotografiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FotografiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fotografia');
    }
}