<?php

/**
 * PedidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PedidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PedidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pedido');
    }
    
    public function findCurrentByUserId($userId) {
      $q = Doctrine_Query::create()
        ->from('Pedido')
        ->addWhere('is_pagado = ?', false)
        ->addWhere('user_id = ?', $userId);
      return $q->fetchOne();
    }
}