<?php

/**
 * PedidoItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PedidoItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PedidoItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PedidoItem');
    }
}