<?php

/**
 * sfGuardUserProfileFotografiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfileFotografiaTable extends Doctrine_Table
{
  public static function getInstance() {
      return Doctrine_Core::getTable('sfGuardUserProfileFotografia');
  }

  public function findOneByUserAndFoto($user_id, $foto_id) {
    $q = $this->createQuery('a')
      ->addWhere('a.sf_guard_user_profile_id = ?', $user_id)
      ->addWhere('a.fotografia_id = ?', $foto_id);
    return $q->fetchOne();
  }
}