<?php

/**
 * BusquedaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BusquedaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BusquedaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Busqueda');
    }
}