<?php

/**
 * FotografiaLugarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FotografiaLugarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FotografiaLugarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FotografiaLugar');
    }
}