<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/19 22:56:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=hormigon_fotiaradm',
  'username' => 'hormigon',
  'password' => 'H0rm160n',
  'name' => 'doctrine',
)),);
