<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/03/19 22:56:35
$this->security = array (
  'index' => 
  array (
    'is_secure' => true,
  ),
  'papelera' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
